version: '3.8'

services:
  
  vault-server:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json